# Generated by Django 3.2.7 on 2021-09-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='FIO',
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('name', 'surname', 'middlename', 'organization')},
        ),
    ]
