# Generated by Django 3.2.7 on 2021-09-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210912_1646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('name', 'surname', 'middlename', 'organization'), name='unique_employee'),
        ),
    ]
