# Generated by Django 3.2.7 on 2021-09-01 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210901_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fax',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Формат телефонного номера: "+00000000000".Максимум - 15 символов (+71234567890).', regex='^\\+?1?\\d{8,15}$')], verbose_name='Факс'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Формат телефонного номера: "+00000000000".Максимум - 15 символов (+71234567890).', regex='^\\+?1?\\d{8,15}$')], verbose_name='Личный телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Формат телефонного номера: "+00000000000".Максимум - 15 символов (+71234567890).', regex='^\\+?1?\\d{8,15}$')], verbose_name='Рабочий телефон'),
        ),
    ]
